name: Auto-Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  auto-deploy:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Update Deployment Time
        run: |
          sed -i "/Last deployment time:/c\Last deployment time: $(date '+%Y/%m/%d %H:%M:%S')" README.md || echo "Last deployment time: $(date '+%Y/%m/%d %H:%M:%S')" >> README.md

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: a commit keep choreo always online
          branch: main
          push_options: '--force'

      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{ github.repository }}
          workflow: ".github/workflows/auto-deploy.yml"
          older-than-seconds: 3600
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
